version: '3'
services:
  pawn-api:
    build: .
    environment:
      - DATABASE_URL=postgres://postgres:postgres@postgres:5432/pawn?schema=public
    ports:
      - '3000:3000'
    depends_on:
      - postgres
  postgres:
    image: postgres:alpine
    ports:
      - '2345:5432'
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=pawn
